#!/usr/bin/env bash
#Prints different strings depending on while loop iteration
x=1
while [ $x -le 10 ]
do
	if [ $x == 4 ]
	then
		echo "bad luck"
	elif [ $x == 8 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi

	x=$(( x + 1 ))
done
