#!/usr/bin/env bash
#Prints ertian strings depending on file status
if [ -e "holbertonschool" ]
then
	echo "holbertonschool file exists"

	if [ -s "holbertonschool" ]
	then
		echo "holbertonschool file is not empty"
	else
		echo "holbertonschool file is empty"
	fi

	if [ -f "holbertonschool" ]
	then
		echo "holbertonschool file is a regular file"
	fi
else
	echo "holbertonschool file does not exist"
fi
